-- TravelMind cloud storage migration.
-- Safe to run against the existing project: it never deletes or rewrites itinerary rows.

begin;

create table if not exists public.travelmind_data (
    id bigint generated by default as identity primary key,
    code text not null,
    data jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create unique index if not exists travelmind_data_code_unique
    on public.travelmind_data (code);

alter table public.travelmind_data enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.travelmind_data to anon, authenticated;

-- Preserve existing policies. Only initialize a fresh table when it has none.
do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'travelmind_data'
    ) then
        create policy travelmind_select_room
            on public.travelmind_data
            for select
            to anon, authenticated
            using (code ~ '^[0-9]{4}$');

        create policy travelmind_insert_room
            on public.travelmind_data
            for insert
            to anon, authenticated
            with check (code ~ '^[0-9]{4}$');

        create policy travelmind_update_room
            on public.travelmind_data
            for update
            to anon, authenticated
            using (code ~ '^[0-9]{4}$')
            with check (code ~ '^[0-9]{4}$');
    end if;
end $$;

commit;
